{% set name = "pluggy" %}
{% set version = "1.0.0.dev0" %}
{% set sha256 = "6c20d4de0d59e6d7960e1e85aac6ed2f7d57dfe982a37048d74e245451e6493a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name [0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - importlib_metadata >=0.12  # [py<38]

test:
  imports:
    - pluggy

about:
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plugin registration and hook calling for Python'
  doc_url: https://pluggy.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pluggy/

extra:
  recipe-maintainers:
    - johnnygenomics
    - nicoddemus
    - adriendelsalle
